Drop nvram entry from qemu.conf
The `nvram = [ ... ]` entry in qemu.conf is now obsolete, so long as the
more modern method of installing a JSON descriptor file in
`/etc/qemu/firmware/` is used.

A related but separate issue is that libvirt 5.10 is unable to create
UEFI VMs, with the following error message:

    libvirt.libvirtError: operation failed: unable to find any master
    var store for loader: /usr/share/ovmf/x64/OVMF_CODE.fd

Weirdly, adding the following entry to the `<os>` section of the VM's
XML definition fixes the issue:

    <nvram template="/usr/share/ovmf/x64/OVMF_VARS.fd">/var/lib/libvirt/qemu/nvram/win10_VARS.fd</nvram>